[package]
name = "fx"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.0"
regex = "1.5.6"
dirs = "4.0.0"
serde = { version = "1.0.137", features = ["derive"] }
toml = "0.5.9"
glob = "0.3.0"
